classdef Optimizer
    %UNTITLED3 Summary of this class goes here
    %   Detailed explanation goes here

    properties
        window
        windowLabel
        modeToggleLabel
        modeToggle %screening only / optimization only / full
        
        
        % Screening GUI elements
        screeningModeToggleLabel
        screeningModeToggle % DOE / bayes
        binaryInputLabel
        entropyCheckbox
        blankCheckbox
        contaminantCheckbox
        isotopeCheckbox
        peakAlignCheckbox
        baselineCheckbox
        smoothingCheckbox

        optModeToggle % DOE / bayes
        optModeToggleLabel
        floatInputLabel
        intThreshField
        mzErrorField
        minRoiField
        minPeakWidthField
        maxPeakWidthField
        mzTolField
        timeTolField
        minSNField
        maxShiftnegField
        maxShiftposField
        pulseWidthField
        iterationField
        gridStepField
        windowSizeField
        stepSizeField
        frameSizeField
        polyDegreeField
        %%
        intThreshFieldLabel
        mzErrorFieldLabel
        minRoiFieldLabel
        minPeakWidthFieldLabel
        maxPeakWidthFieldLabel
        mzTolFieldLabel
        timeTolFieldLabel
        minSNFieldLabel
        maxShiftnegFieldLabel
        maxShiftposFieldLabel
        pulseWidthFieldLabel
        iterationFieldLabel
        gridStepFieldLabel
        windowSizeFieldLabel
        stepSizeFieldLabel
        frameSizeFieldLabel
        polyDegreeFieldLabel
    end

    methods
        function obj = Optimizer(callingData)
            %UNTITLED3 Construct an instance of this class
            %   Detailed explanation goes here
            obj.window =  uifigure(Position=[100,100,680,520],...
                Name="Setting Optimizer",...
                Visible="on");

            obj.windowLabel = uilabel(obj.window,"Text","Setting optimizer",...
                "Position",[10,475,250,50],...
                FontName="Impact",...
                FontSize=28,...
                FontWeight="normal");

            obj.modeToggleLabel = uilabel(obj.window,"Text","Processing Mode:",...
                "Position",[10,435,100,30]);
            obj.modeToggle = uidropdown(obj.window,...
                "Items",["Screening only","Optimization only","Combined"],...
                "ItemsData",["Screening","Optimization","Combined"],...
                "Value","Screening",...
                Position=[110,435,130,30],...
                Tooltip="under construction");

            obj.screeningModeToggleLabel = uilabel(obj.window,"Text","Screening Mode:",...
                "Position",[10,400,100,30]);
            obj.screeningModeToggle = uidropdown(obj.window,...
                "Items",["d-optimal DOE","Bayesian"],...
                "ItemsData",["DOE","bayes"],...
                "Value","DOE",...
                Position=[110,400,130,30],...
                Enable="off");

            obj.optModeToggleLabel = uilabel(obj.window,"Text","Optimization Mode:",...
                "Position",[270,400,110,30]);
            obj.optModeToggle = uidropdown(obj.window,...
                "Items",["d-optimal DOE","Bayesian"],...
                "ItemsData",["DOE","bayes"],...
                "Value","DOE",...
                Position=[380,400,130,30],...
                Enable="off");

            obj.binaryInputLabel = uilabel(obj.window,"Text","Specify binary options:",...
                "Position",[10,360,200,20],...
                "FontSize",15,...
                FontWeight="bold");

            obj.entropyCheckbox = uicheckbox(obj.window,...
                "Value",callingData.EntropyFilter,...
                "Position",[20,330,120,20],...
                "Text","Entropy filter",...
                Tooltip="Includes the entropy peak filter in the screening process.");

            obj.blankCheckbox = uicheckbox(obj.window,...
                "Value",callingData.BLKSubtraction,...
                "Position",[150,330,120,20],...
                "Text","Blank Subtraction",...
                Tooltip="Includes the subtraction of blank files in the screening process.");

            obj.contaminantCheckbox = uicheckbox(obj.window,...
                "Value",callingData.ContaminantFilter,...
                "Position",[280,330,175,20],...
                "Text","Contaminant Filter",...
                Tooltip="Removes all features with masses listed in the UWPR Common Mass Spec Contaminants list.");

            obj.peakAlignCheckbox = uicheckbox(obj.window,...
                "Value",callingData.Peakalign,...
                "Position",[20,300,175,20],...
                "Text","Peak Alignment",...
                Tooltip="Aligns peaks between files to reference peaks. For each ROI the highest signal is used as reference peak. First, it creates a synthetic signal from the reference peaks using Gaussian pulses centered at the separation-unit values specified by the reference peak. Then, it shifts and scales the separation-unit scale to find the maximum alignment between the input signals and the synthetic signal. (It uses an iterative multiresolution grid search until it finds the best scale and shift factors for each signal.) Once the new separation-unit scale is determined, the corrected signals are created by resampling their intensities at the original separation-unit values. The resampling method preserves the shape of the peaks.");

            obj.isotopeCheckbox = uicheckbox(obj.window,...
                "Value",callingData.IsotopeFilter,...
                "Position",[150,300,175,20],...
                "Text","Isotope Filter",...
                Tooltip="Removes isotopic peaks. Verified are peak shape, intensity related to isotope abundance, retention time and mass tolerance.");

            obj.baselineCheckbox = uicheckbox(obj.window,...
                "Value",callingData.BaseCorr,...
                "Position",[280,300,175,20],...
                "Text","Baseline Correction",...
                Tooltip="Corrects variable baseline by estimating the baseline within multiple shifted windows, regressing the varying baseline to the window points using a spline approximation, then adjusting the baseline of the peak signals.");

            obj.smoothingCheckbox = uicheckbox(obj.window,...
                "Value",callingData.Smoothing,...
                "Position",[410,300,175,20],...
                "Text","Golay Smoothing",...
                Tooltip="Smoothing of the signals using a Savitzky-Golay filter.");

            obj.floatInputLabel = uilabel(obj.window,"Text","Specify levels:",...
                "Position",[10,260,200,20],...
                "FontSize",15,...
                FontWeight="bold");
            %% add callbackfunctions
            obj.modeToggle.ValueChangedFcn = @(src,event) {ProcessingModeValueChange(obj,src,event)};

            %% float inputs
            obj.intThreshField = uieditfield(obj.window,...
                "InputType","alphanumerics",...
                Position=[130,230,150,20],...
                Enable="on");
            obj.intThreshFieldLabel = uilabel(obj.window,"Text","Intensity threshold:",...
                "Position",[20,230,120,20],...
                Enable="on");

            obj.mzErrorField = uieditfield(obj.window,...
                "InputType","alphanumerics",...
                Position=[130,200,150,20],...
                Enable="on");
            obj.mzErrorFieldLabel = uilabel(obj.window,"Text","MZ error:",...
                "Position",[20,200,120,20],...
                Enable="on");

            obj.minRoiField = uieditfield(obj.window,...
                "InputType","alphanumerics",...
                Position=[130,170,150,20],...
                Enable="on");
            obj.minRoiFieldLabel = uilabel(obj.window,"Text","min. ROI size:",...
                "Position",[20,170,120,20],...
                Enable="on");
            
            obj.minPeakWidthField = uieditfield(obj.window,...
                "InputType","alphanumerics",...
                Position=[130,140,150,20],...
                Enable="on");
            obj.minPeakWidthFieldLabel = uilabel(obj.window,"Text","min. Peak width:",...
                "Position",[20,140,120,20],...
                Enable="on");
        
            obj.maxPeakWidthField = uieditfield(obj.window,...
                "InputType","alphanumerics",...
                Position=[130,110,150,20],...
                Enable="on");
            obj.maxPeakWidthFieldLabel = uilabel(obj.window,"Text","max. Peak width:",...
                "Position",[20,110,120,20],...
                Enable="on");
            
            obj.mzTolField = uieditfield(obj.window,...
                "InputType","alphanumerics",...
                Position=[130,80,150,20],...
                Enable="on");
            obj.mzTolFieldLabel = uilabel(obj.window,"Text","MZ tolerance:",...
                "Position",[20,80,120,20],...
                Enable="on");
            
            obj.timeTolField = uieditfield(obj.window,...
                "InputType","alphanumerics",...
                Position=[130,50,150,20],...
                Enable="on");
            obj.timeTolFieldLabel = uilabel(obj.window,"Text","time tolerance:",...
                "Position",[20,50,120,20],...
                Enable="on");
            
            obj.minSNField = uieditfield(obj.window,...
                "InputType","alphanumerics",...
                Position=[130,20,150,20],...
                Enable="on");
            obj.minSNFieldLabel = uilabel(obj.window,"Text","min. Signal to Noise:",...
                "Position",[20,20,120,20],...
                Enable="on");

            % obj.maxShiftnegField
            % obj.maxShiftposField
            % obj.pulseWidthField
            % obj.iterationField
            % obj.gridStepField
            % obj.windowSizeField
            % obj.stepSizeField
            % obj.frameSizeField
            % obj.polyDegreeField
        end
        
        function obj = ProcessingModeValueChange(obj,src,event)
            %METHOD1 Summary of this method goes here
            %   Detailed explanation goes here
            if obj.modeToggle.Value == "Screening"
                obj.screeningModeToggle.Enable = "on";
                obj.optModeToggle.Enable = "off";

            elseif obj.modeToggle.Value == "Optimization"
                obj.screeningModeToggle.Enable = "off";
                obj.optModeToggle.Enable = "on";
            else 
                obj.screeningModeToggle.Enable = "on";
                obj.optModeToggle.Enable = "on";
            end
        end

        function obj = CheckboxValueChange(obj)

        end

        function outputArg = CheckUserStringInput(obj,inputArg)
            %METHOD1 Summary of this method goes here
            %   Detailed explanation goes here
            outputArg = obj.Property1 + inputArg;
        end

        function outputArg = GatherInputs(obj,inputArg)
            %METHOD1 Summary of this method goes here
            %   Detailed explanation goes here
            outputArg = obj.Property1 + inputArg;
        end

        function outputArg = DOEScreening(obj,inputArg)
            %METHOD1 Summary of this method goes here
            %   Detailed explanation goes here
            outputArg = obj.Property1 + inputArg;
        end

        function outputArg = BayesScreening(obj,inputArg)
            %METHOD1 Summary of this method goes here
            %   Detailed explanation goes here
            outputArg = obj.Property1 + inputArg;
        end

        function outputArg = DOEOptimization(obj,inputArg)
            %METHOD1 Summary of this method goes here
            %   Detailed explanation goes here
            outputArg = obj.Property1 + inputArg;
        end

        function outputArg = BayesOptimization(obj,inputArg)
            %METHOD1 Summary of this method goes here
            %   Detailed explanation goes here
            outputArg = obj.Property1 + inputArg;
        end
    end
end