classdef BaseCorrOptions
    %UNTITLED Summary of this class goes here
    %   Detailed explanation goes here

    properties
        Container 
        WindowSizeField
        StepSizeField
        RegressionDrop
        EstimationDrop
        SmoothDrop
        QuantilValField
        Labels
    end

    methods
        function obj = BaseCorrOptions(CallingTab,CallingData)
            %UNTITLED Construct an instance of this class
            %   Detailed explanation goes here            
            obj.Container = uipanel(CallingTab,"Title","Baseline Correction Parameters", ...
                "BackgroundColor",[0.90,0.90,0.90], ...
                "Position",[465,10,220,180], ...
                "TitlePosition","centertop",...
                FontWeight="bold",Enable="off");

            obj.WindowSizeField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,130,90,20], ...
                "Limits",[1,Inf], ...
                "ValueDisplayFormat","%.0f scans",...
                "Value",CallingData.WindowSize, ...
                "RoundFractionalValues","on");
            obj.Labels(1) = uilabel(obj.Container,"Text","Window Size","Position",[5,130,110,20],"HorizontalAlignment","right");

            obj.StepSizeField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,105,90,20], ...
                "Limits",[1,Inf], ...
                "ValueDisplayFormat","%.0f scans",...
                "Value",CallingData.StepSize, ...
                "RoundFractionalValues","on");
            obj.Labels(2) = uilabel(obj.Container,"Text","Step Size","Position",[5,105,110,20],"HorizontalAlignment","right");
            
            obj.RegressionDrop = uidropdown(obj.Container,...
                "Value",CallingData.RegressionMethod,...
                "Items",["Shape-preserving piecewise cubic interpolation","Linear Interpolation","Spline Interpolation"],...
                "ItemsData",["pchip","linear","spline"],...
                "Position",[125,80,90,20]);
            obj.Labels(3) = uilabel(obj.Container,"Text","Regression Method","Position",[5,80,110,20],"HorizontalAlignment","right");

            obj.EstimationDrop = uidropdown(obj.Container,...
                "Value",CallingData.EstimationMethod,...
                "Items",["Quantile","Estimation-Maximization"],...
                "ItemsData",["quantile","em"],...
                "Position",[125,55,90,20]);
            obj.Labels(4) = uilabel(obj.Container,"Text","Estimation Method","Position",[5,55,110,20],"HorizontalAlignment","right");

            obj.SmoothDrop = uidropdown(obj.Container,...
                "Value",CallingData.SmoothMethod,...
                "Items",["No Smoothing","Linear fit","Quadratic fit","Robust linear fit","Robust quadratic fit"],...
                "ItemsData",["none","lowess","loess","rlowess","rloess"],...
                "Position",[125,30,90,20]);
            obj.Labels(5) = uilabel(obj.Container,"Text","Smoothing Method","Position",[5,30,110,20],"HorizontalAlignment","right");

            obj.QuantilValField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,5,90,20], ...
                "Limits",[0,1], ...
                "ValueDisplayFormat","%11.4g",...
                "Value",CallingData.QuantilVal, ...
                "RoundFractionalValues","off");
            obj.Labels(6) = uilabel(obj.Container,"Text","Quantile Value","Position",[5,5,110,20],"HorizontalAlignment","right");

        end
    end
end