classdef FeatData
    %Class object for storing and processing of feature data generated by
    % AriumMS RawData objects. Input: merged output struct containing all
    % feature data (intensities, retention times, numeric identifier
    % (column 1 mass, column 2 RT), Peak Borders. Calculates and stores
    % Average Intensity, number of occurrences, p-Values, Fold Changes
    % and Standard Deviation, and applies data transformations and scaling.

    properties
        GroupName                   (1,:) string
        AbstractGroupName           (1,:) string
        FullUnscaledIntensityArray  (:,:) double
        CleanFullIntensityArray     (:,:) double
        IntensityArray              (:,:) double
        IdentifierArray             (:,:) double
        XIC                         (:,:) cell
        NameStringArray             (:,1) string
        RetentionTimeArray          (:,:) double
        EntropyArray                (:,:) double
        Signal2NoiseArray           (:,:) double
        NumberOfFilesArray          (1,:) double
        OccurenceCount              (:,:) double
        SignificantFeature          (1,:) cell
        UniqueFeature               (:,:) logical
        AverageIntensities          (:,:) double
        StandardDeviations          (:,:) double
        FullFoldChanges             (1,:) cell
        VSNaming                    (1,:) cell
        FoundInReferenceGroup       (1,:) cell
        OriginalGroup               (:,:) string
        InGroup                     (:,:) string
        CombinedSampleNames         (1,:) cell
        MSnSpectra                  (:,:) cell
        FilteredMSnSpectra          (:,:) cell
        FeatureMSnSpectra           (:,1) cell
        dataBaseResultsMS1          (:,1) cell
        dataBaseResultsMS2          (:,1) cell
        DBScoreSpectraID            (:,:) cell
        DataBaseSpectra             (:,:) cell
    end

    methods
        function obj = FeatData(FullOutput)
            %UNTITLED Construct an instance of this class
            %   Detailed explanation goes here
            obj.GroupName = FullOutput.GroupName(1,:);
            if size(FullOutput.GroupName,1)>1
                obj.AbstractGroupName =  "Augmented Group " + FullOutput.GroupName(2,:);
            end
            %remove duplicate rows
            [obj.IdentifierArray,ia,~] = unique(FullOutput.FeatIdentifiers,"rows");

            obj.FullUnscaledIntensityArray = FullOutput.IntensityStorage(ia,:);
            obj.RetentionTimeArray = FullOutput.RetentionTimeStorage(ia,:);
            obj.NumberOfFilesArray = FullOutput.SampleNumbers;
            obj.EntropyArray = FullOutput.EntropyStorage(ia,:);
            obj.Signal2NoiseArray = FullOutput.Signal2NoiseStorage(ia,:);
            obj.XIC = FullOutput.XIC(ia,:);
            if iscell(FullOutput.SampleNames)
                obj.CombinedSampleNames = FullOutput.SampleNames;
            else
                obj.CombinedSampleNames{1}=FullOutput.SampleNames;
            end

            if isfield(FullOutput,"OriginalGroup")
                obj.OriginalGroup = FullOutput.OriginalGroup(ia,:);
            else
                obj.OriginalGroup = repmat(obj.GroupName,size(obj.IdentifierArray,1),1);
            end

            obj = obj.BuildInGroupString;
            obj.NameStringArray = obj.IdentifierArray(:,1) + "@" + obj.IdentifierArray(:,2) + "s,"+ obj.InGroup;
            Subgroups = obj.FullUnscaledIntensityArray;
            Subgroups(Subgroups==0)=NaN;
            Subgroups = mat2cell(Subgroups,size(Subgroups,1),obj.NumberOfFilesArray);
            %replace missing by average value of that feature
            parfor q=1:size(Subgroups,2)
                mat=Subgroups{q};
                for row = 1:size(mat,1)
                    missingIndices = isnan(mat(row, :));
                    rowMean = mean(mat(row, ~missingIndices));
                    mat(row, missingIndices) = rowMean;
                end
                Subgroups{q}=mat;
            end
            obj.CleanFullIntensityArray = horzcat(Subgroups{:});
            obj.IntensityArray = obj.CleanFullIntensityArray;

            obj = obj.GetOccurencesAndUniqueness;
            obj = obj.CalculateAveragesAndSTD;
            obj = obj.CalculateFoldChanges;
        end

        function obj = BuildInGroupString(obj)
            % Initialize mergedString array
            mergedString = cell(size(obj.OriginalGroup, 1), 1);
            % Iterate through each row
            for i = 1:size(obj.OriginalGroup, 1)
                % Concatenate non-empty strings with the appropriate delimiter
                mergedString{i} = strjoin(obj.OriginalGroup(i, ~cellfun('isempty', obj.OriginalGroup(i, :))), ', ');
            end
            obj.InGroup = string(mergedString);
            %remove  unnecessary delimiters in InGroup
            InGroupString = obj.InGroup;
            parfor n=1:size(obj.InGroup,1)
                ExtractedString=split(InGroupString(n),",");
                ExtractedString(ExtractedString=="")=[];
                InGroupString(n) = join(ExtractedString,",");
            end
            obj.InGroup= InGroupString;
        end

        function  obj = GetOccurencesAndUniqueness(obj)
            %clear old Array
            obj.UniqueFeature = [];
            % get number of Occurrences per Group
            Subgroups = obj.FullUnscaledIntensityArray;
            Subgroups(Subgroups==0)=NaN;
            Subgroups(~isnan(Subgroups)) = 1;
            Subgroups = mat2cell(Subgroups,size(Subgroups,1),obj.NumberOfFilesArray);
            NumCounts = cellfun(@(x) sum(x,2,'omitnan'), Subgroups, 'UniformOutput', false);
            obj.OccurenceCount = horzcat(NumCounts{:});
            % check for Feature Uniqueness
            for n=1:size(obj.OccurenceCount,2)
                currentgroup = obj.OccurenceCount(:,n);
                othergroups = obj.OccurenceCount;
                othergroups(:,n) = [];
                obj.UniqueFeature(:,n) = currentgroup > 0 & sum(othergroups,2) == 0;
            end
        end

        function obj = CalculateAveragesAndSTD(obj)
            %calculate Average Intensity and standard Deviation for all
            %Features
            Subgroups = obj.IntensityArray;
            Subgroups(Subgroups==0)=NaN;
            Subgroups = mat2cell(Subgroups,size(Subgroups,1),obj.NumberOfFilesArray);
            AverageIntensityCell=cellfun(@(x) mean(x,2,'omitnan'),Subgroups,'UniformOutput',false);
            obj.AverageIntensities = horzcat(AverageIntensityCell{:});
            StandardDeviationCell=horzcat(cellfun(@(x) std(x,[],2,'omitnan'),Subgroups,'UniformOutput',false));
            obj.StandardDeviations = horzcat(StandardDeviationCell{:});

        end

        function obj = CalculateFoldChanges(obj)
            for g=1:size(obj.GroupName,2)
                Averages = obj.AverageIntensities;
                AllNames = obj.GroupName;
                idx = contains(AllNames,"+");
                AllNames(idx) = obj.AbstractGroupName(idx);
                ActiveGroup = Averages(:,g);
                ActiveName = AllNames(g);
                AllNames(g) = [];
                Averages(:,g)=[];
                %preallocation
                FoldArray = zeros(size(Averages));
                VSNamingArray = strings(size(AllNames));
                %calculate fold-changes against each group
                for n=1:size(Averages,2)
                    BaseLineGroup = Averages(:,n);
                    BaseLineName = AllNames(n);
                    fold = ActiveGroup./BaseLineGroup;
                    fold(isinf(fold))=0;
                    fold(isnan(fold))=0; %replace possible NaN and Inf with 0;
                    FoldArray(:,n) = fold;
                    VSNamingArray(n) = ActiveName + " vs. " + BaseLineName;
                end
                obj.FullFoldChanges{g} = FoldArray;
                obj.VSNaming{g} = VSNamingArray;
            end
        end

        function obj = CalculateSignificance(obj,HochbergFilter,FDRValue)
            %calculate feature significance only for non unique features
            AllIntensities = mat2cell(obj.IntensityArray,size(obj.IntensityArray,1),obj.NumberOfFilesArray);
            for g=1:size(obj.GroupName,2)
                ActiveGroup = AllIntensities{g};
                OtherGroups = AllIntensities(1:end ~= g);
                SignificantFeatureArray = zeros(size(ActiveGroup,1),size(OtherGroups,2));
                for n=1:size(OtherGroups,2)
                    [~,p]=ttest2(ActiveGroup,OtherGroups{n},'Vartype','unequal',"Dim",2);
                    p(isnan(p))=1;
                    if HochbergFilter==true
                        [~,sortParam]=sort(p,'ascend');
                        rank=1:1:length(p);
                        rank=rank(sortParam);
                        ptest=(rank/length(rank))*FDRValue;
                        idx=ptest'<=0.05;
                        p(idx)=NaN;
                    end
                    SignificantFeatureArray(:,n) = p;
                end
                obj.SignificantFeature{g}=SignificantFeatureArray;
            end
        end

        function obj = applyFeatureScaling(obj,TransformType,ScaleType)
            FeatIntensity = obj.CleanFullIntensityArray;
            FeatIntensity(FeatIntensity==0)=NaN;
            %% Transform
            switch TransformType
                case 'logn'
                    FeatIntensity = log(FeatIntensity);
                case 'log10'
                    FeatIntensity = log10(FeatIntensity);
                case 'power'
                    FeatIntensity = sqrt(FeatIntensity);
                case 'cube'
                    FeatIntensity = FeatIntensity.^(1/3);
                case 'reciprocal'
                    FeatIntensity = FeatIntensity.^-1;
            end
            %% scale each feature along 2nd dimension (sample repetition)
            %scaled individually excluding NaN
            FeatIntensity(FeatIntensity==0)=NaN;
            FeatIntensity(FeatIntensity==Inf)=NaN;
            FeatIntensity(FeatIntensity==-Inf)=NaN;
            switch ScaleType
                case 'Centering' %only mean centering
                    FeatIntensity=FeatIntensity-mean(FeatIntensity,2,'omitnan');
                case 'Auto' %z score
                    FeatIntensity=(FeatIntensity-mean(FeatIntensity,2,'omitnan'))./std(FeatIntensity,0,2,'omitnan');
                case 'Pareto' %Pareto scaling
                    FeatIntensity = (FeatIntensity-mean(FeatIntensity,2,'omitnan'))./sqrt(std(FeatIntensity,0,2,'omitnan'));
                case 'Vast' %Vast scaling
                    FeatIntensity = ((FeatIntensity-mean(FeatIntensity,2,'omitnan'))./std(FeatIntensity,0,2,'omitnan')).*(mean(FeatIntensity,2,'omitnan')./std(FeatIntensity,0,2,'omitnan'));
                case 'Range' %range [min max] scaling
                    FeatIntensity = (FeatIntensity-mean(FeatIntensity,2,'omitnan'))./(max(FeatIntensity,[],2,'omitnan')-min(FeatIntensity,[],2,'omitnan'));
                case 'Level' %Level Scaling
                    FeatIntensity = (FeatIntensity-mean(FeatIntensity,2,'omitnan'))./mean(FeatIntensity,2,'omitnan');
            end
            FeatIntensity(FeatIntensity==Inf)=0;
            FeatIntensity(FeatIntensity==-Inf)=0;
            FeatIntensity(isnan(FeatIntensity))=0;
            obj.IntensityArray = FeatIntensity;

            %update Average Intensity, standard Deviation
            obj = obj.CalculateAveragesAndSTD;
            obj = obj.CalculateFoldChanges;

        end

        function obj = RefGroupScaling(obj,GroupAssignment)
            if all(GroupAssignment(:,2)=='none')
                text="no Reference Group selected";
                notInRef{1,1}=repmat(text,size(obj.IdentifierArray,1),1);
                obj.FoundInReferenceGroup=repmat(notInRef,size(obj.NumberOfFilesArray));

            else
                %calculate Averages
                Subgroups = obj.CleanFullIntensityArray;
                Subgroups(Subgroups==0)=NaN;
                Subgroups = mat2cell(Subgroups,size(Subgroups,1),obj.NumberOfFilesArray);
                AverageIntensityCell=cellfun(@(x) mean(x,2,'omitnan'),Subgroups,'UniformOutput',false);
                % get Indices for Assignment
                GroupAssignment=removecats(GroupAssignment);    %remove unused categories
                Uni=unique(GroupAssignment(:,1));
                Ref=GroupAssignment(:,2)==Uni'; % row = Sample Group, Col = Reference Group
                [SampleGroupID,ReferenceGroupID]=find(Ref);
                if any(any(Ref,2))==true
                    notInRef=cell(size(Subgroups));
                    text = strings(size(obj.FullUnscaledIntensityArray,1),1);
                    for n=1:length(SampleGroupID)
                        ref=AverageIntensityCell{ReferenceGroupID(n)};
                        samp=Subgroups{SampleGroupID(n)};
                        idx=~isnan(ref);
                        idx(:,2)=all(~isnan(samp),2);
                        TextID = idx(:,1) == false & idx(:,2) == true;
                        text(TextID) = "not found in Reference Group";
                        notInRef{SampleGroupID(n)} = text;
                        idx=any(~idx,2);
                        samp(~idx,:)=samp(~idx,:)./ref(~idx);
                        Subgroups{SampleGroupID(n)}=samp;
                    end
                    obj.IntensityArray = horzcat(Subgroups{:});
                    obj.FoundInReferenceGroup = notInRef;
                    idx = cellfun(@(x) isempty(x), obj.FoundInReferenceGroup);
                    text = "no Reference Group";
                    text = repmat(text,size(obj.IntensityArray,1),1);
                    obj.FoundInReferenceGroup(idx) = {text};
                else
                    text="no Reference Group";
                    notInRef{1,1}=repmat(text,size(obj.IntensityArray,1),1);
                    obj.FoundInReferenceGroup=repmat(notInRef,size(Subgroups));
                end
            end
        end

        function obj = AssignSpectra2Features(obj,RawDataArray)
            %%%%%%%%%%%%%
            % test tolerances
            mzTol = 0.05;
            TolUnit = "Da";
            RTTol = 60;
            mergeMZtol = 0.015;
            %%%%%%%%%%%%%
            GroupNames = [RawDataArray.GroupName];
            Storage = cell(size(obj.OriginalGroup));
            Storage = reshape(Storage,[],1);
            PeakData = cell(size(RawDataArray));
            TimeData = cell(size(RawDataArray));
            Precursor = cell(size(RawDataArray));
            % FragType = cell(size(RawDataArray));
            % FragEnergy = cell(size(RawDataArray));
            %gather MS2Data
            parfor n=1:size(RawDataArray,2)
                PeakData{n} = vertcat(RawDataArray(n).PeakDataMSn{:});
                TimeData{n} = vertcat(RawDataArray(n).TimeDataMSn{:});
                % FragType{n} = vertcat(RawDataArray(n).CollisionType{:});
                % FragEnergy{n} = vertcat(RawDataArray(n).CollisionEnergy{:});
                %convert pseudo-molecular ion precursor to molecular
                %precursor
                switch RawDataArray(n).MSPolarity
                    case "negative"
                        Precursor{n} = round(vertcat(RawDataArray(n).Precursor{:}) + 1.007825,5);
                    case "positive"
                        Precursor{n} = round(vertcat(RawDataArray(n).Precursor{:}) - 1.007825,5);
                end
            end
            FeatMZ = obj.IdentifierArray(:,1);
            FeatMZ = repmat(FeatMZ,1,size(obj.OriginalGroup,2));
            FeatMZ = reshape(FeatMZ,[],1);
            FeatTime = obj.IdentifierArray(:,2);
            FeatTime = repmat(FeatTime,1,size(obj.OriginalGroup,2));
            FeatTime = reshape(FeatTime,[],1);
            FeatGroups = obj.OriginalGroup;
            FeatGroups = reshape(FeatGroups,[],1);
            parfor nFeat = 1:size(FeatMZ,1)
                FeatGroup = FeatGroups(nFeat);
                %determine which group to search
                [~,index] = ismember(FeatGroup,GroupNames);
                idx = [];
                if strcmp(FeatGroup,"")
                    continue
                else
                    switch TolUnit
                        case "Da"
                            idx = abs(FeatMZ(nFeat)-Precursor{index})<= mzTol & abs(TimeData{index}-FeatTime(nFeat))<= RTTol;
                        case "ppm"
                            idx = abs(((FeatMZ(nFeat)-Precursor{index})/FeatMZ(nFeat))*10^6)<= mzTol & abs(TimeData{index}-FeatTime(nFeat))<= RTTol;
                    end
                    Spectra = PeakData{index}(idx);
                    Times = TimeData{index}(idx);
                    if ~isempty(Spectra)
                        % Sort Spectra time wise
                        [~,index] = sort(Times,'ascend');
                        Spectra = Spectra(index);
                        %merge Spectra into matrix
                        Spectra = mergeMatricesWithTolerance(Spectra,mergeMZtol,"Da");
                        %sort Spectra matrix with ascending m/z
                        [~,order] = sort(Spectra(:,1),'ascend');
                        Storage{nFeat,1} = Spectra(order,:);
                    end
                end
            end
            obj.MSnSpectra = reshape(Storage,size(obj.OriginalGroup));
            %calculate all scores within a feature
            InnerScores = cellfun(@InnerFeatScores,obj.MSnSpectra,'UniformOutput',false);
            % merge spectra with score >=850
            obj.FilteredMSnSpectra = cellfun(@FilterSameSpectra,obj.MSnSpectra,InnerScores,'UniformOutput',false);

        end



        function obj = BTEMCrossRef(obj)
            %check if multiple spectra per Feature

            %perform SVD to determine number of possible species
            Intensities = cellfun(@(x) x(:,2:end),obj.MSnSpectra,'UniformOutput',false);
            NumSpecies = cellfun(@DetermineNumComponents,Intensities,'UniformOutput',false);
            idx = cellfun(@isempty,NumSpecies);
            NumSpecies(idx) = {0};
            NumSpecies = cell2mat(NumSpecies);
            HasMultiple = NumSpecies > 1;
            %perform BTEM to calculate pure spectra
            Spectras = obj.MSnSpectra;
            PureSpectra = cell(size(Spectras));
            [row,col] = size(HasMultiple);
            for c = 1:col
                for r = 1:row
                    if HasMultiple(r,c) == false
                        continue
                    else
                        Data = Spectras{r,c}(:,2:end);
                        Masses = Spectras{r,c}(:,1);
                        SusComp = NumSpecies(r,c);
                        PureSpectra{r,c} = PerformBTEM(Data,Masses,SusComp);
                    end
                end
            end

            % compare pure spectra with spectra of features with same mass
        end

        function obj = ScoresWithinGroups(obj)
            %%%%%%%%%%%%%
            % test tolerances
            mzTol = 0.05;
            TolUnit = "Da";
            mergeMZtol = 0.015;
            %%%%%%%%%%%%%
            RemoveRow = [];
            mzlist = obj.IdentifierArray(:,1);
            uniqueMZ = unique(mzlist);
            Spectra = obj.FilteredMSnSpectra;
            numGroups = size(Spectra,2);
            for n = 1:length(uniqueMZ)
                id = mzlist == uniqueMZ(n);
                SubSpectra = Spectra(id,:);
                for G = 1:numGroups
                    QuerySpectra = SubSpectra(:,G);
                    row = find(id);
                    idx = cellfun(@isempty, QuerySpectra);
                    QuerySpectra(idx) = [];
                    row(idx) = [];
                    if size(QuerySpectra,1) < 2
                        continue
                    end
                    WithinScores = OuterFeatScores(QuerySpectra',mzTol,TolUnit);
                    WithinScores = vertcat(WithinScores{:});
                    if all(WithinScores(:,1)<750) %no matching Spectra
                        continue
                    else
                        %get features to merge
                        Spectra{row(1),G} = mergeMatricesWithTolerance(QuerySpectra,mergeMZtol,"Da");
                        %store row Index for deletion
                        RemoveRow = [RemoveRow;row(2:end)];
                    end
                end
            end
            %remove duplicate feature rows
            RemoveRow = unique(RemoveRow);
            Spectra(RemoveRow,:)=[];
            obj.FilteredMSnSpectra = Spectra;
            obj.FullUnscaledIntensityArray(RemoveRow,:)=[];
            obj.CleanFullIntensityArray(RemoveRow,:)=[];
            obj.IntensityArray(RemoveRow,:)=[];
            obj.IdentifierArray(RemoveRow,:)=[];
            obj.XIC(RemoveRow,:)=[];
            obj.NameStringArray(RemoveRow,:)=[];
            obj.RetentionTimeArray(RemoveRow,:)=[];
            obj.EntropyArray(RemoveRow,:)=[];
            obj.Signal2NoiseArray(RemoveRow,:)=[];
            obj.OccurenceCount(RemoveRow,:)=[];
            obj.InGroup(RemoveRow,:)=[];
            obj.OriginalGroup(RemoveRow,:)=[];
            obj.UniqueFeature(RemoveRow,:)=[];
            obj.AverageIntensities(RemoveRow,:)=[];
            obj.StandardDeviations(RemoveRow,:)=[];
            %FoldChanges
            obj = obj.CalculateFoldChanges;
        end

        function obj = ProcessGroupMSnSpectra(obj)
            %%%%%%%%%%%%%
            % test tolerances
            mzTol = 0.05;
            mzTolUnit = "Da";
            mergeMZtol = 0.015;
            %%%%%%%%%%%%%
            obj = obj.ScoresWithinGroups;
            MeasuredSpectra = obj.FilteredMSnSpectra;
            GroupScores =  OuterFeatScores(MeasuredSpectra,mzTol,mzTolUnit);
            hasMatch = false(size(GroupScores,1),1);
            parfor n = 1:size(hasMatch,1)
                if isempty(GroupScores{n})
                    continue
                else
                    hasMatch(n,1) = any(GroupScores{n,1}(:,1)>=750,"all");
                end
            end

            FullMerge = cell(size(hasMatch));

            for n = 1:size(hasMatch,1)
                if hasMatch(n) == true
                    %keep matching spectra
                    Spectra = MeasuredSpectra(n,:);
                    ScoresAndID = GroupScores(n,:);
                    for Group = 1:size(ScoresAndID,2)
                    rowID = ScoresAndID{1,Group}(:,1)>=750;
                    SpecID = ScoresAndID{1,Group}(rowID,2);
                    SpecID = SpecID+1; %because first row are m/z values
                    Storage = cell(size(Spectra,2),1);
                        if ~isempty(Spectra{1,Group})
                            Storage{Group,1} = Spectra{1,Group}(:,[1,unique(SpecID(:,1)')]);
                        end
                    end
                    %remove empty
                    id = cellfun(@isempty,Storage);
                    Storage(id) = [];
                    if size(Storage,1) > 1
                        FullMerge{n,1} = mergeMatricesWithTolerance(Storage,mergeMZtol,"Da");
                    elseif size(Storage,1) == 1
                        FullMerge(n,1) = Storage;
                    end
                    
                    continue

                elseif hasMatch(n) == false & ~isempty(GroupScores{n,1})
                    %% no matching spectra split features
                    % spectra
                    Spectra = MeasuredSpectra(n,:);
                    id = cellfun(@isempty,Spectra);
                    Spectra(id) = [];
                    FullMerge(n,1) = Spectra(1);
                    Spectra(1) = [];
                    %expand Cell array
                    for Deal = 1:size(Spectra,2)
                        %deal remaining
                        FullMerge(end+1,1) = Spectra(1,Deal);
                    end

                    %% update remaining FeatData
                    %Matrices
                    %FullUnscaledIntensityArray
                    ZeroVec = zeros(1,sum(obj.NumberOfFilesArray));
                    ZeroVec = mat2cell(ZeroVec,1,obj.NumberOfFilesArray);
                    Subgroups = obj.FullUnscaledIntensityArray;
                    Subgroups = mat2cell(Subgroups,ones(size(Subgroups,1),1),obj.NumberOfFilesArray);
                    Data = Subgroups(n,2:end);
                    Vec = zeros(1,sum(obj.NumberOfFilesArray));
                    Vec = mat2cell(Vec,1,obj.NumberOfFilesArray);
                    %expand Cell array
                    for Deal = 1:size(Spectra,2)
                        Subgroups(end+1,:) = Vec;
                        %deal remaining
                        Subgroups(end,Deal+1) = Data(1,Deal);
                    end
                    obj.FullUnscaledIntensityArray = cell2mat(Subgroups);

                    %CleanFullIntensityArray
                    Subgroups = obj.CleanFullIntensityArray;
                    Subgroups = mat2cell(Subgroups,ones(size(Subgroups,1),1),obj.NumberOfFilesArray);
                    Data = Subgroups(n,2:end);
                    Vec = zeros(1,sum(obj.NumberOfFilesArray));
                    Vec = mat2cell(Vec,1,obj.NumberOfFilesArray);
                    %expand Cell array
                    for Deal = 1:size(Spectra,2)
                        Subgroups(end+1,:) = Vec;
                        %deal remaining
                        Subgroups(end,Deal+1) = Data(1,Deal);
                    end
                    obj.CleanFullIntensityArray = cell2mat(Subgroups);

                    %IntensityArray
                    Subgroups = obj.IntensityArray;
                    Subgroups = mat2cell(Subgroups,ones(size(Subgroups,1),1),obj.NumberOfFilesArray);
                    Data = Subgroups(n,2:end);
                    Vec = zeros(1,sum(obj.NumberOfFilesArray));
                    Vec = mat2cell(Vec,1,obj.NumberOfFilesArray);
                    %expand Cell array
                    for Deal = 1:size(Spectra,2)
                        Subgroups(end+1,:) = Vec;
                        %deal remaining
                        Subgroups(end,Deal+1) = Data(1,Deal);
                    end
                    obj.IntensityArray = cell2mat(Subgroups);

                    %EntropyArray
                    Subgroups = obj.EntropyArray;
                    Subgroups = mat2cell(Subgroups,ones(size(Subgroups,1),1),obj.NumberOfFilesArray);
                    Data = Subgroups(n,2:end);
                    Vec = zeros(1,sum(obj.NumberOfFilesArray));
                    Vec = mat2cell(Vec,1,obj.NumberOfFilesArray);
                    %expand Cell array
                    for Deal = 1:size(Spectra,2)
                        Subgroups(end+1,:) = Vec;
                        %deal remaining
                        Subgroups(end,Deal+1) = Data(1,Deal);
                    end
                    obj.EntropyArray = cell2mat(Subgroups);

                    %RetentionTimeArray
                    Subgroups = obj.RetentionTimeArray;
                    Subgroups = mat2cell(Subgroups,ones(size(Subgroups,1),1),obj.NumberOfFilesArray);
                    Data = Subgroups(n,2:end);
                   Vec = zeros(1,sum(obj.NumberOfFilesArray));
                    Vec = mat2cell(Vec,1,obj.NumberOfFilesArray);
                    %expand Cell array
                    for Deal = 1:size(Spectra,2)
                        Subgroups(end+1,:) = Vec;
                        %deal remaining
                        Subgroups(end,Deal+1) = Data(1,Deal);
                    end
                    obj.RetentionTimeArray = cell2mat(Subgroups);

                    %Signal2NoiseArray
                    Subgroups = obj.Signal2NoiseArray;
                    Subgroups = mat2cell(Subgroups,ones(size(Subgroups,1),1),obj.NumberOfFilesArray);
                    Data = Subgroups(n,2:end);
                    Vec = zeros(1,sum(obj.NumberOfFilesArray));
                    Vec = mat2cell(Vec,1,obj.NumberOfFilesArray);
                    %expand Cell array
                    for Deal = 1:size(Spectra,2)
                        Subgroups(end+1,:) = Vec;
                        %deal remaining
                        Subgroups(end,Deal+1) = Data(1,Deal);
                    end
                    obj.Signal2NoiseArray = cell2mat(Subgroups);

                    %cells
                    %XIC
                    Subgroups = obj.XIC;
                    Subgroups = mat2cell(Subgroups,ones(size(Subgroups,1),1),obj.NumberOfFilesArray);
                    Data = Subgroups(n,2:end);
                    Vec = cell(1,sum(obj.NumberOfFilesArray));
                    Vec = mat2cell(Vec,1,obj.NumberOfFilesArray);
                    %expand Cell array
                    for Deal = 1:size(Spectra,2)
                        Subgroups(end+1,:) = Vec;
                        %deal remaining
                        Subgroups(end,Deal+1) = Data(1,Deal);
                    end
                    Subgroups = [Subgroups{:}];
                    obj.XIC = reshape(Subgroups,[],sum(obj.NumberOfFilesArray));

                    %IdentifierArray
                    for Deal = 1:size(Spectra,2)
                        obj.IdentifierArray(end+1,:) = obj.IdentifierArray(n,:);
                    end

                    %OriginalGroup
                    OGroup = obj.OriginalGroup(n,:);
                    %expand Cell array
                    for Deal = 1:size(Spectra,2)
                        obj.OriginalGroup(end+1,size(obj.OriginalGroup,2)) = string;
                        %deal remaining
                        obj.OriginalGroup(end,Deal) = OGroup(1,Deal);
                    end
               
                else % store single group spectra
                    Spectra = MeasuredSpectra(n,:);
                    id = cellfun(@isempty,Spectra);
                    Spectra(id) = [];
                    if ~isempty(Spectra)
                        FullMerge(n,1) = Spectra;
                    end
                end
            end

            
            %% recalculate stuff
            %AverageIntensities and StandardDeviation
            obj = obj.CalculateAveragesAndSTD;

            %OccurenceCount and UniqueFeature
            obj = obj.GetOccurencesAndUniqueness;

            %FoldChanges
            obj = obj.CalculateFoldChanges;

            %InGroup
            obj = obj.BuildInGroupString;
            %NameStringArray
            obj.NameStringArray = obj.IdentifierArray(:,1) + "@" + obj.IdentifierArray(:,2) + "s,"+ obj.InGroup;

            %store final Feature Spectra
            obj.FeatureMSnSpectra = FullMerge;
        end
    end
end

