classdef IntegrationOptions
% BSD 3-Clause License
% 
% Copyright (c) 2022, Adrian Haun
% All rights reserved.
% 
% Redistribution and use in source and binary forms, with or without
% modification, are permitted provided that the following conditions are met:
% 
% 1. Redistributions of source code must retain the above copyright notice, this
%    list of conditions and the following disclaimer.
% 
% 2. Redistributions in binary form must reproduce the above copyright notice,
%    this list of conditions and the following disclaimer in the documentation
%    and/or other materials provided with the distribution.
% 
% 3. Neither the name of the copyright holder nor the names of its
%    contributors may be used to endorse or promote products derived from
%    this software without specific prior written permission.
% 
% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
% AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
% IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
% DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
% FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
% DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
% SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
% CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
% OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
% OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

    properties
        Container 
        EntropyCheck
        OccurrenceField
        minSNField
        maxWidthField
        minWidthField
        EvalParamDrop
        mzTolField
        mzTolUnitDrop
        RTTolField
        Labels 
    end

    methods
        function obj = IntegrationOptions(CallingTab,CallingData)
            %UNTITLED2 Construct an instance of this class
            %   Detailed explanation goes here
            
            obj.Container = uipanel(CallingTab,"Title","Peak Picking and Filter Options", ...
                "BackgroundColor",[0.90,0.90,0.90], ...
                "Position",[240,325,220,230], ...
                "TitlePosition","centertop",...
                "FontWeight","bold",Enable="off");

            obj.EvalParamDrop = uidropdown(obj.Container, ...
                "Items",["Peak Area","Peak Height"],...
                ItemsData=["Area","Height"], ...
                Value=CallingData.EvaluationParameter,...
                Position=[125,180,90,20],...
                Tooltip="Specify whether peak heights or areas are to be used for evaluation.");
            
            obj.Labels(1) = uilabel(obj.Container,"Text","Evaluation","Position",[5,180,110,20],"HorizontalAlignment","right");

            obj.minWidthField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,155,90,20], ...
                "Limits",[0.01,Inf], ...
                "ValueDisplayFormat","%.1f s",...
                "Value",CallingData.minWidth, ...
                "RoundFractionalValues","off",...
                Tooltip="Filters peaks with smaller width. Recommended setting: Just below width of the narrowest peak in the BPC.");
            
            obj.Labels(2) = uilabel(obj.Container,"Text","min. Peak Width","Position",[5,155,110,20],"HorizontalAlignment","right");

            obj.maxWidthField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,130,90,20], ...
                "Limits",[1,Inf], ...
                "ValueDisplayFormat","%.1f s",...
                "Value",CallingData.maxWidth, ...
                "RoundFractionalValues","off",...
                Tooltip="Filters peaks with greater width. Recommended setting: Just above width of the broadest peak in the BPC.");
            
            obj.Labels(3) = uilabel(obj.Container,"Text","max. Peak Width","Position",[5,130,110,20],"HorizontalAlignment","right");

            obj.minSNField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,105,90,20], ...
                "Limits",[1,Inf], ...
                "ValueDisplayFormat","%.0f",...
                "Value",CallingData.minSignalNoise, ...
                "RoundFractionalValues","off",...
                Tooltip="Filters peaks with lower signal to noise. Recommended setting: 3 or higher.");
            
            obj.Labels(4) = uilabel(obj.Container,"Text","min. Signal to Noise","Position",[5,105,110,20],"HorizontalAlignment","right");

             obj.OccurrenceField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,80,90,20], ...
                "Limits",[1,100], ...
                "ValueDisplayFormat","%.1f %%",...
                "Value",CallingData.minOccurence*100, ...
                "RoundFractionalValues","off",...
                Tooltip="Removes features found in too few repeated measurements. Recommended setting: >50% ");
            
            obj.Labels(5) = uilabel(obj.Container,"Text","min. Occurence","Position",[5,80,110,20],"HorizontalAlignment","right");
            
             obj.mzTolField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,55,40,20], ...
                "Limits",[0,Inf], ...
                "Value",CallingData.mzTol, ...
                "RoundFractionalValues","off",...
                Tooltip="Mass tolerance, whether peaks from different replicate measurements belong to the same feature. Also used for the m/z tolerances of the adduct/neutral loss filter, isotope filter, contaminant filter, and internal standard detection. Recommended setting: Instrument mass accuracy");
            obj.Labels(1) = uilabel(obj.Container,"Text","mz Tolerance","Position",[5,55,110,20],HorizontalAlignment="right");

            obj.mzTolUnitDrop = uidropdown(obj.Container, ...
                "Items",["ppm","Da"],...
                ItemsData=["ppm","Da"], ...
                Value=CallingData.mzErrorUnit,...
                Position=[165,55,50,20],...
                Tooltip="Specify whether a fixed mz error in Da or a relative error in ppm is used.");

            obj.RTTolField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,30,90,20], ...
                "Limits",[0,Inf], ...
                "ValueDisplayFormat","%.1f s",...
                "Value",CallingData.RTTol, ...
                "RoundFractionalValues","off",...
                ToolTip="Retention time tolerance whether peaks from different replicate measurements belong to the same feature.");
            obj.Labels(2) = uilabel(obj.Container,"Text","Time Tolerance","Position",[5,30,110,20],HorizontalAlignment="right");

            obj.EntropyCheck = uicheckbox(obj.Container,...
                Value=CallingData.EntropyFilter,...
                Position=[10,5,175,20],...
                Text="Peak Entropy Filter",...
                Tooltip="Filters peaks by peak entropy. The median entropy of all peaks in the group is used as the maximum allowed entropy.");

        end
    end
end