classdef IntegrationOptions
    %UNTITLED2 Summary of this class goes here
    %   Detailed explanation goes here

    properties
        Container 
        EntropyCheck
        OccurrenceField
        minSNField
        maxWidthField
        minWidthField
        EvalParamDrop
        mzTolField
        RTTolField
        Labels 
    end

    methods
        function obj = IntegrationOptions(CallingTab,CallingData)
            %UNTITLED2 Construct an instance of this class
            %   Detailed explanation goes here
            
            obj.Container = uipanel(CallingTab,"Title","Peak Picking and Filter Options", ...
                "BackgroundColor",[0.90,0.90,0.90], ...
                "Position",[240,325,220,230], ...
                "TitlePosition","centertop",...
                "FontWeight","bold",Enable="off");

            obj.EvalParamDrop = uidropdown(obj.Container, ...
                "Items",["Peak Area","Peak Height"],...
                ItemsData=["Area","Height"], ...
                Value=CallingData.EvaluationParameter,...
                Position=[125,180,90,20]);
            
            obj.Labels(1) = uilabel(obj.Container,"Text","Evaluation","Position",[5,180,110,20],"HorizontalAlignment","right");

            obj.minWidthField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,155,90,20], ...
                "Limits",[0.01,Inf], ...
                "ValueDisplayFormat","%.1f s",...
                "Value",CallingData.minWidth, ...
                "RoundFractionalValues","off");
            
            obj.Labels(2) = uilabel(obj.Container,"Text","min. Peak Width","Position",[5,155,110,20],"HorizontalAlignment","right");

            obj.maxWidthField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,130,90,20], ...
                "Limits",[1,Inf], ...
                "ValueDisplayFormat","%.1f s",...
                "Value",CallingData.maxWidth, ...
                "RoundFractionalValues","off");
            
            obj.Labels(3) = uilabel(obj.Container,"Text","max. Peak Width","Position",[5,130,110,20],"HorizontalAlignment","right");

            obj.minSNField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,105,90,20], ...
                "Limits",[1,Inf], ...
                "ValueDisplayFormat","%.0f",...
                "Value",CallingData.minSignalNoise, ...
                "RoundFractionalValues","off");
            
            obj.Labels(4) = uilabel(obj.Container,"Text","min. Signal to Noise","Position",[5,105,110,20],"HorizontalAlignment","right");

             obj.OccurrenceField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,80,90,20], ...
                "Limits",[1,100], ...
                "ValueDisplayFormat","%.1f %%",...
                "Value",CallingData.minOccurence*100, ...
                "RoundFractionalValues","off");
            
            obj.Labels(5) = uilabel(obj.Container,"Text","min. Occurence","Position",[5,80,110,20],"HorizontalAlignment","right");
            
             obj.mzTolField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,55,90,20], ...
                "Limits",[0,Inf], ...
                "ValueDisplayFormat","%.5f Da",...
                "Value",CallingData.mzTol, ...
                "RoundFractionalValues","off");
            obj.Labels(1) = uilabel(obj.Container,"Text","mz Tolerance","Position",[5,55,110,20],HorizontalAlignment="right");

            obj.RTTolField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,30,90,20], ...
                "Limits",[0,Inf], ...
                "ValueDisplayFormat","%.1f s",...
                "Value",CallingData.RTTol, ...
                "RoundFractionalValues","off");
            obj.Labels(2) = uilabel(obj.Container,"Text","Time Tolerance","Position",[5,30,110,20],HorizontalAlignment="right");

            obj.EntropyCheck = uicheckbox(obj.Container,...
                Value=CallingData.EntropyFilter,...
                Position=[10,5,175,20],...
                Text="Peak Entropy Filter");

        end
    end
end