classdef IntegrationOptions
%% Object for storing Integration and Peak filter option UI elements

    properties
        Container 
        EntropyCheck
        OccurrenceField
        minSNField
        maxWidthField
        minWidthField
        EvalParamDrop
        mzTolField
        mzTolUnitDrop
        RTTolField
        Labels 
    end

    methods
        function obj = IntegrationOptions(CallingTab,CallingData)
            %UNTITLED2 Construct an instance of this class
            %   Detailed explanation goes here
            
            obj.Container = uipanel(CallingTab,"Title","Peak Picking and Filter Options", ...
                "BackgroundColor",[0.90,0.90,0.90], ...
                "Position",[240,325,220,230], ...
                "TitlePosition","centertop",...
                "FontWeight","bold",Enable="off");

            obj.EvalParamDrop = uidropdown(obj.Container, ...
                "Items",["Peak Area","Peak Height"],...
                ItemsData=["Area","Height"], ...
                Value=CallingData.EvaluationParameter,...
                Position=[125,180,90,20],...
                Tooltip="Specify whether peak heights or areas are to be used for evaluation.");
            
            obj.Labels(1) = uilabel(obj.Container,"Text","Evaluation","Position",[5,180,110,20],"HorizontalAlignment","right");

            obj.minWidthField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,155,90,20], ...
                "Limits",[0.01,Inf], ...
                "ValueDisplayFormat","%.1f s",...
                "Value",CallingData.minWidth, ...
                "RoundFractionalValues","off",...
                Tooltip="Filters peaks with smaller width. Recommended setting: Just below width of the narrowest peak in the BPC.");
            
            obj.Labels(2) = uilabel(obj.Container,"Text","min. Peak Width","Position",[5,155,110,20],"HorizontalAlignment","right");

            obj.maxWidthField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,130,90,20], ...
                "Limits",[1,Inf], ...
                "ValueDisplayFormat","%.1f s",...
                "Value",CallingData.maxWidth, ...
                "RoundFractionalValues","off",...
                Tooltip="Filters peaks with greater width. Recommended setting: Just above width of the broadest peak in the BPC.");
            
            obj.Labels(3) = uilabel(obj.Container,"Text","max. Peak Width","Position",[5,130,110,20],"HorizontalAlignment","right");

            obj.minSNField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,105,90,20], ...
                "Limits",[1,Inf], ...
                "ValueDisplayFormat","%.0f",...
                "Value",CallingData.minSignalNoise, ...
                "RoundFractionalValues","off",...
                Tooltip="Filters peaks with lower signal to noise. Recommended setting: 3 or higher.");
            
            obj.Labels(4) = uilabel(obj.Container,"Text","min. Signal to Noise","Position",[5,105,110,20],"HorizontalAlignment","right");

             obj.OccurrenceField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,80,90,20], ...
                "Limits",[1,100], ...
                "ValueDisplayFormat","%.1f %%",...
                "Value",CallingData.minOccurence*100, ...
                "RoundFractionalValues","off",...
                Tooltip="Removes features found in too few repeated measurements. Recommended setting: >50% ");
            
            obj.Labels(5) = uilabel(obj.Container,"Text","min. Occurence","Position",[5,80,110,20],"HorizontalAlignment","right");
            
             obj.mzTolField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,55,40,20], ...
                "Limits",[0,Inf], ...
                "Value",CallingData.mzTol, ...
                "RoundFractionalValues","off",...
                Tooltip="Mass tolerance, whether peaks from different replicate measurements belong to the same feature. Also used for the m/z tolerances of the adduct/neutral loss filter, isotope filter, contaminant filter, and internal standard detection. Recommended setting: Instrument mass accuracy");
            obj.Labels(1) = uilabel(obj.Container,"Text","mz Tolerance","Position",[5,55,110,20],HorizontalAlignment="right");

            obj.mzTolUnitDrop = uidropdown(obj.Container, ...
                "Items",["ppm","Da"],...
                ItemsData=["ppm","Da"], ...
                Value=CallingData.mzErrorUnit,...
                Position=[165,55,50,20],...
                Tooltip="Specify whether a fixed mz error in Da or a relative error in ppm is used.");

            obj.RTTolField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,30,90,20], ...
                "Limits",[0,Inf], ...
                "ValueDisplayFormat","%.1f s",...
                "Value",CallingData.RTTol, ...
                "RoundFractionalValues","off",...
                ToolTip="Retention time tolerance whether peaks from different replicate measurements belong to the same feature.");
            obj.Labels(2) = uilabel(obj.Container,"Text","Time Tolerance","Position",[5,30,110,20],HorizontalAlignment="right");

            obj.EntropyCheck = uicheckbox(obj.Container,...
                Value=CallingData.EntropyFilter,...
                Position=[10,5,175,20],...
                Text="Peak Entropy Filter",...
                Tooltip="Filters peaks by peak entropy. The median entropy of all peaks in the group is used as the maximum allowed entropy.");

        end
    end
end