classdef ISOptions
    %UNTITLED Summary of this class goes here
    %   Detailed explanation goes here

    properties
        Container
        NumberSelect
        MassCalCheck
        ApplyDrop
        ApplyLabel matlab.ui.control.Label
        OrderDrop
        OrderLabel matlab.ui.control.Label
        DefineButton
        StatusLamp
        Labels
        window
        InputTable
        OKButton
        oldDat
    end

    methods
        function obj = ISOptions(CallingTab,CallingData)
            obj.oldDat = CallingData.ISDat;
            %UNTITLED Construct an instance of this class
            %   Detailed explanation goes here
            obj.Container = uipanel(CallingTab,...
                "Title","Internal Standard Options",...
                FontWeight="bold",...
                Position=[695,10,220,180],...
                TitlePosition="centertop",...
                BackgroundColor=[0.90,0.90,0.90],Enable="off");

            obj.NumberSelect = uispinner(obj.Container,...
                Limits=[1,Inf],Value=CallingData.numISTD,...
                Step=1,...
                Position=[125,125,90,20],...
                ValueDisplayFormat="%.0f",...
                RoundFractionalValues="on");
            obj.Labels(1)  = uilabel(obj.Container,"Text",["Number of","Internal Standards"],"Position",[5,115,110,40],"HorizontalAlignment","right",WordWrap=true);
            
            obj.MassCalCheck = uicheckbox(obj.Container,...
                Value=CallingData.MassCal,...
                Position=[10,25,175,20],...
                Text="Mass Correction");

            obj.ApplyDrop = uidropdown(obj.Container,...
                "Value",CallingData.ISApply,...
                "Items",["Samples and Blanks","Samples only"],...
                "ItemsData",["S&B","SOnly"],...
                "Position",[105,95,110,20],"Enable",CallingData.BLKSubtraction);
            obj.ApplyLabel = uilabel(obj.Container,"Text","Apply to","Position",[5,95,90,20],"Enable",CallingData.BLKSubtraction,HorizontalAlignment="right");

            obj.OrderDrop = uidropdown(obj.Container,...
                "Value",CallingData.ISOrder,...
                "Items",["Blank then IS","IS then blank"],...
                "ItemsData",["BlankIS","ISBlank"],...
                "Position",[105,65,110,20],...
                "Enable",CallingData.BLKSubtraction);
            obj.OrderLabel = uilabel(obj.Container,"Text","Normalization order","Position",[5,55,90,40],"Enable",CallingData.BLKSubtraction,HorizontalAlignment="right",WordWrap="on");

            obj.DefineButton = uibutton(obj.Container,...
                "Text","Define ISTD",...
                "Position",[125,15,90,40]);

            obj.StatusLamp = uilamp(obj.Container,...
                "Position",[200,162.5,15,15]);
            if isempty(obj.oldDat) == true
               obj.StatusLamp.Color=[1.00,0.00,0.00];
            else
                obj.StatusLamp.Color=[0.39,0.83,0.07];
            end
        end
        
    end
end