classdef MSAlignOptions
    %UNTITLED2 Summary of this class goes here
    %   Detailed explanation goes here

    properties
        Container 
        QuantilField
        EstimationDrop
        CorrectionDrop
        Labels
    end

    methods
        function obj = MSAlignOptions(CallingTab,CallingData)
            %UNTITLED2 Construct an instance of this class
            %   Detailed explanation goes here
            
            obj.Container = uipanel(CallingTab,"Title","Spectral Alignment Parameters", ...
                "BackgroundColor",[0.90,0.90,0.90], ...
                "Position",[240,215,220,105], ...
                "TitlePosition","centertop",...
                "FontWeight","bold",Enable="off");

            obj.QuantilField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,55,90,20], ...
                "Limits",[0,1], ...
                "ValueDisplayFormat","%11.4g",...
                "Value",CallingData.mzQuantil, ...
                "RoundFractionalValues","off");
            
            obj.Labels(1) = uilabel(obj.Container,"Text","Quantil Value","Position",[5,55,110,20],"HorizontalAlignment","right");

            obj.EstimationDrop = uidropdown(obj.Container, ...
                "Items",["Histogram","Regression"],...
                ItemsData=["histogram","regression"], ...
                Value=CallingData.mzEstimMethod,...
                Position=[125,30,90,20]);
            
            obj.Labels(2) = uilabel(obj.Container,"Text","Estimation Method","Position",[5,30,110,20],"HorizontalAlignment","right");

            obj.CorrectionDrop = uidropdown(obj.Container, ...
                "Items",["Nearest Neighbor","Shortest Path"],...
                ItemsData=["nearest-neighbor","shortest-path"], ...
                Value=CallingData.mzCorrectionMethod,...
                Position=[125,5,90,20]);
            
            obj.Labels(3) = uilabel(obj.Container,"Text","Correction Method","Position",[5,5,110,20],"HorizontalAlignment","right");
        end
    end
end