classdef ROIOptions
    % BSD 3-Clause License
% 
% Copyright (c) 2022, Adrian Haun
% All rights reserved.
% 
% Redistribution and use in source and binary forms, with or without
% modification, are permitted provided that the following conditions are met:
% 
% 1. Redistributions of source code must retain the above copyright notice, this
%    list of conditions and the following disclaimer.
% 
% 2. Redistributions in binary form must reproduce the above copyright notice,
%    this list of conditions and the following disclaimer in the documentation
%    and/or other materials provided with the distribution.
% 
% 3. Neither the name of the copyright holder nor the names of its
%    contributors may be used to endorse or promote products derived from
%    this software without specific prior written permission.
% 
% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
% AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
% IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
% DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
% FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
% DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
% SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
% CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
% OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
% OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

    properties
        Container       
        ThreshField     matlab.ui.control.NumericEditField
        mzerrorField    matlab.ui.control.NumericEditField
        mzerrorUnitDrop
        minROIField     matlab.ui.control.NumericEditField
        StartTimeField  matlab.ui.control.NumericEditField
        EndTimeField    matlab.ui.control.NumericEditField
        Labels
    end

    methods
        function obj = ROIOptions(CallingTab,CallingData)
            %UNTITLED Construct an instance of this class
            %   Detailed explanation goes here
         
            obj.Container = uipanel(CallingTab,"Title","ROI Parameters", ...
                "BackgroundColor",[0.90,0.90,0.90], ...
                "Position",[10,80,220,150], ...
                "FontWeight","bold",...
                "TitlePosition","centertop",Enable="off");
            
            obj.ThreshField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,105,90,20], ...
                "Limits",[1,Inf], ...
                "ValueDisplayFormat","%.0f",...
                "Value",CallingData.thresh, ...
                "RoundFractionalValues","on",...
                "Tooltip","Minimum signal intensity required for inclusion in ROI. Recommended setting: 5-10% of BPC baseline intensity");
            obj.Labels(1) = uilabel(obj.Container,"Text","Intensity Threshold","Position",[5,105,110,20],HorizontalAlignment="right");

            obj.mzerrorField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,80,40,20], ...
                "Limits",[0,Inf], ...
                "LowerLimitInclusive","off",...
                "Value",CallingData.mzerror,...
                Tooltip="m/z difference in Da where ROI masses are considered to be within the same ROI. Recommended setting: Instrument mass accuracy");
            obj.Labels(2) = uilabel(obj.Container,"Text","MZ error","Position",[5,80,110,20],HorizontalAlignment="right");

            obj.mzerrorUnitDrop = uidropdown(obj.Container, ...
                "Items",["ppm","Da"],...
                ItemsData=["ppm","Da"], ...
                Value=CallingData.mzErrorUnit,...
                Position=[165,80,50,20],...
                Tooltip="Specify whether a fixed mz error in Da or a relative error in ppm is used.");

            obj.minROIField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,55,90,20], ...
                "Limits",[1,Inf], ...
                "LowerLimitInclusive","off",...
                "ValueDisplayFormat","%.0f scans",...
                "Value",CallingData.minroi, ...
                "RoundFractionalValues","on",...
                Tooltip="Minimum number of scans a m/z must be above the intensity threshold to be considered as ROI. Recommended setting: Number of data points for narrowest peak");
            obj.Labels(3) = uilabel(obj.Container,"Text","Minimum ROI size","Position",[5,55,110,20],HorizontalAlignment="right");

            obj.StartTimeField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,30,90,20], ...
                "Limits",[CallingData.Start, CallingData.End], ...
                "LowerLimitInclusive","on",...
                "ValueDisplayFormat","%.1f s",...
                "Value",CallingData.Start,...
                Tooltip="Removes data points before the specified retention time. Recommended setting: A few seconds before the first relevant peak");
            obj.Labels(4) = uilabel(obj.Container,"Text","Start Time","Position",[5,30,110,20],HorizontalAlignment="right");

            obj.EndTimeField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,5,90,20], ...
                "Limits",[CallingData.Start + 0.1 ,CallingData.End], ...
                "UpperLimitInclusive","on",...
                "ValueDisplayFormat","%.1f s",...
                "Value",CallingData.End,...
                Tooltip="Removes data points after the specified retention time. Recommended setting: A few seconds after the last relevant peak");
            obj.Labels(5) = uilabel(obj.Container,"Text","End Time","Position",[5,5,110,20],HorizontalAlignment="right");
        end        
    end
end