classdef ROIOptions
%% Object for storing ROI Options UI elements

    properties
        Container       
        ThreshField     matlab.ui.control.NumericEditField
        mzerrorField    matlab.ui.control.NumericEditField
        mzerrorUnitDrop
        minROIField     matlab.ui.control.NumericEditField
        StartTimeField  matlab.ui.control.NumericEditField
        EndTimeField    matlab.ui.control.NumericEditField
        Labels
    end

    methods
        function obj = ROIOptions(CallingTab,CallingData)
            %UNTITLED Construct an instance of this class
            %   Detailed explanation goes here
         
            obj.Container = uipanel(CallingTab,"Title","ROI Parameters", ...
                "BackgroundColor",[0.90,0.90,0.90], ...
                "Position",[10,80,220,150], ...
                "FontWeight","bold",...
                "TitlePosition","centertop",Enable="off");
            
            obj.ThreshField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,105,90,20], ...
                "Limits",[1,Inf], ...
                "ValueDisplayFormat","%.0f",...
                "Value",CallingData.thresh, ...
                "RoundFractionalValues","on",...
                "Tooltip","Minimum signal intensity required for inclusion in ROI. Recommended setting: 5-10% of BPC baseline intensity");
            obj.Labels(1) = uilabel(obj.Container,"Text","Intensity Threshold","Position",[5,105,110,20],HorizontalAlignment="right");

            obj.mzerrorField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,80,40,20], ...
                "Limits",[0,Inf], ...
                "LowerLimitInclusive","off",...
                "Value",CallingData.mzerror,...
                Tooltip="m/z difference in Da where ROI masses are considered to be within the same ROI. Recommended setting: Instrument mass accuracy");
            obj.Labels(2) = uilabel(obj.Container,"Text","MZ error","Position",[5,80,110,20],HorizontalAlignment="right");

            obj.mzerrorUnitDrop = uidropdown(obj.Container, ...
                "Items",["ppm","Da"],...
                ItemsData=["ppm","Da"], ...
                Value=CallingData.mzErrorUnit,...
                Position=[165,80,50,20],...
                Tooltip="Specify whether a fixed mz error in Da or a relative error in ppm is used.");

            obj.minROIField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,55,90,20], ...
                "Limits",[1,Inf], ...
                "LowerLimitInclusive","off",...
                "ValueDisplayFormat","%.0f scans",...
                "Value",CallingData.minroi, ...
                "RoundFractionalValues","on",...
                Tooltip="Minimum number of scans a m/z must be above the intensity threshold to be considered as ROI. Recommended setting: Number of data points for narrowest peak");
            obj.Labels(3) = uilabel(obj.Container,"Text","Minimum ROI size","Position",[5,55,110,20],HorizontalAlignment="right");

            obj.StartTimeField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,30,90,20], ...
                "Limits",[CallingData.Start, CallingData.End], ...
                "LowerLimitInclusive","on",...
                "ValueDisplayFormat","%.1f s",...
                "Value",CallingData.Start,...
                Tooltip="Removes data points before the specified retention time. Recommended setting: A few seconds before the first relevant peak");
            obj.Labels(4) = uilabel(obj.Container,"Text","Start Time","Position",[5,30,110,20],HorizontalAlignment="right");

            obj.EndTimeField = uieditfield(obj.Container,"numeric", ...
                "Position",[125,5,90,20], ...
                "Limits",[CallingData.Start + 0.1 ,CallingData.End], ...
                "UpperLimitInclusive","on",...
                "ValueDisplayFormat","%.1f s",...
                "Value",CallingData.End,...
                Tooltip="Removes data points after the specified retention time. Recommended setting: A few seconds after the last relevant peak");
            obj.Labels(5) = uilabel(obj.Container,"Text","End Time","Position",[5,5,110,20],HorizontalAlignment="right");
        end        
    end
end